apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - rbac.yaml
  - release-pipeline-sa.yaml
  - regcred-empty.yaml
  - appstudio-pipeline-integration-runner-rbac.yaml
  - application-and-component.yaml
  - ec-integration-test.yaml
  - integration-test-hello.yaml
  - release-plan.yaml
  - jira-collectors-secret.yaml
